services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_NAME}
    volumes:
      - ./database/init-roles.sh:/docker-entrypoint-initdb.d/init-roles.sh
volumes:
  postgres_data: